#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
APP="$1";
IMAGE_TAG="$2";
IMAGE=$(get_app_image_name $APP $IMAGE_TAG);
FILE_ROOT="$DOKKU_ROOT/$APP/DOKKU_ALL_FILES"
verify_app_name "$APP"

if [[ -d "$FILE_ROOT" ]] && [[ -n $(ls -p "$FILE_ROOT") ]]; then
    dokku_log_info1 "Copying all files into image..."
    id=$(docker cp $FILE_ROOT $IMAGE:/home/ /bin/bash -c "cat > /app/$file" < "$path")
fi
